# Generated by Django 6.0.3 on 2026-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to the institution's logo", null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='theme_color',
            field=models.CharField(default='#6366f1', help_text='HEX color code for institutional branding', max_length=7),
        ),
    ]
