# Generated by Django 6.0.3 on 2026-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_system', '0002_college_logo_url_college_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='creprofile',
            name='allocated_colleges',
            field=models.ManyToManyField(blank=True, related_name='assigned_cres', to='admission_system.college'),
        ),
    ]
