# Generated by Django 4.2.29 on 2026-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_system', '0005_application_addon_course_application_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status for dashboard access'),
        ),
    ]
