# Generated by Django 4.2.29 on 2026-04-18 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission_system', '0009_applicationsource_application_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='admission_system.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campus_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
