# Generated by Django 4.2.29 on 2026-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_system', '0010_campusmanagerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Bank Account Number, IFSC Code, Account Name, etc.', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='payment_qr_image',
            field=models.ImageField(blank=True, help_text='Upload static QR code image (if empty, dynamic QR is shown using UPI ID)', null=True, upload_to='college_qrs/'),
        ),
        migrations.AddField(
            model_name='college',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Specific UPI ID for this college (e.g., college@sbi)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='upi_payee_name',
            field=models.CharField(blank=True, help_text='Payee name for UPI (e.g., ABC College)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', '----------'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '----------'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
