# Generated by Django 4.2.24 on 2026-04-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_system', '0011_college_bank_details_college_payment_qr_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference Source'),
        ),
    ]
